// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookstore.proto

package bookstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{1}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type ListShelvesResponse struct {
	Shelves              []*Shelf `protobuf:"bytes,1,rep,name=shelves,proto3" json:"shelves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShelvesResponse) Reset()         { *m = ListShelvesResponse{} }
func (m *ListShelvesResponse) String() string { return proto.CompactTextString(m) }
func (*ListShelvesResponse) ProtoMessage()    {}
func (*ListShelvesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{2}
}

func (m *ListShelvesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShelvesResponse.Unmarshal(m, b)
}
func (m *ListShelvesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShelvesResponse.Marshal(b, m, deterministic)
}
func (m *ListShelvesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShelvesResponse.Merge(m, src)
}
func (m *ListShelvesResponse) XXX_Size() int {
	return xxx_messageInfo_ListShelvesResponse.Size(m)
}
func (m *ListShelvesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShelvesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListShelvesResponse proto.InternalMessageInfo

func (m *ListShelvesResponse) GetShelves() []*Shelf {
	if m != nil {
		return m.Shelves
	}
	return nil
}

type Shelf struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Theme                string   `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shelf) Reset()         { *m = Shelf{} }
func (m *Shelf) String() string { return proto.CompactTextString(m) }
func (*Shelf) ProtoMessage()    {}
func (*Shelf) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{3}
}

func (m *Shelf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shelf.Unmarshal(m, b)
}
func (m *Shelf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shelf.Marshal(b, m, deterministic)
}
func (m *Shelf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shelf.Merge(m, src)
}
func (m *Shelf) XXX_Size() int {
	return xxx_messageInfo_Shelf.Size(m)
}
func (m *Shelf) XXX_DiscardUnknown() {
	xxx_messageInfo_Shelf.DiscardUnknown(m)
}

var xxx_messageInfo_Shelf proto.InternalMessageInfo

func (m *Shelf) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shelf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shelf) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

type CreateShelfParameters struct {
	Shelf                *Shelf   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShelfParameters) Reset()         { *m = CreateShelfParameters{} }
func (m *CreateShelfParameters) String() string { return proto.CompactTextString(m) }
func (*CreateShelfParameters) ProtoMessage()    {}
func (*CreateShelfParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{4}
}

func (m *CreateShelfParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShelfParameters.Unmarshal(m, b)
}
func (m *CreateShelfParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShelfParameters.Marshal(b, m, deterministic)
}
func (m *CreateShelfParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShelfParameters.Merge(m, src)
}
func (m *CreateShelfParameters) XXX_Size() int {
	return xxx_messageInfo_CreateShelfParameters.Size(m)
}
func (m *CreateShelfParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShelfParameters.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShelfParameters proto.InternalMessageInfo

func (m *CreateShelfParameters) GetShelf() *Shelf {
	if m != nil {
		return m.Shelf
	}
	return nil
}

type GetShelfParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShelfParameters) Reset()         { *m = GetShelfParameters{} }
func (m *GetShelfParameters) String() string { return proto.CompactTextString(m) }
func (*GetShelfParameters) ProtoMessage()    {}
func (*GetShelfParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{5}
}

func (m *GetShelfParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShelfParameters.Unmarshal(m, b)
}
func (m *GetShelfParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShelfParameters.Marshal(b, m, deterministic)
}
func (m *GetShelfParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShelfParameters.Merge(m, src)
}
func (m *GetShelfParameters) XXX_Size() int {
	return xxx_messageInfo_GetShelfParameters.Size(m)
}
func (m *GetShelfParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShelfParameters.DiscardUnknown(m)
}

var xxx_messageInfo_GetShelfParameters proto.InternalMessageInfo

func (m *GetShelfParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

type DeleteShelfParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShelfParameters) Reset()         { *m = DeleteShelfParameters{} }
func (m *DeleteShelfParameters) String() string { return proto.CompactTextString(m) }
func (*DeleteShelfParameters) ProtoMessage()    {}
func (*DeleteShelfParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{6}
}

func (m *DeleteShelfParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShelfParameters.Unmarshal(m, b)
}
func (m *DeleteShelfParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShelfParameters.Marshal(b, m, deterministic)
}
func (m *DeleteShelfParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShelfParameters.Merge(m, src)
}
func (m *DeleteShelfParameters) XXX_Size() int {
	return xxx_messageInfo_DeleteShelfParameters.Size(m)
}
func (m *DeleteShelfParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShelfParameters.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShelfParameters proto.InternalMessageInfo

func (m *DeleteShelfParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

type ListBooksParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksParameters) Reset()         { *m = ListBooksParameters{} }
func (m *ListBooksParameters) String() string { return proto.CompactTextString(m) }
func (*ListBooksParameters) ProtoMessage()    {}
func (*ListBooksParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{7}
}

func (m *ListBooksParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksParameters.Unmarshal(m, b)
}
func (m *ListBooksParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksParameters.Marshal(b, m, deterministic)
}
func (m *ListBooksParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksParameters.Merge(m, src)
}
func (m *ListBooksParameters) XXX_Size() int {
	return xxx_messageInfo_ListBooksParameters.Size(m)
}
func (m *ListBooksParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksParameters proto.InternalMessageInfo

func (m *ListBooksParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

type CreateBookParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookParameters) Reset()         { *m = CreateBookParameters{} }
func (m *CreateBookParameters) String() string { return proto.CompactTextString(m) }
func (*CreateBookParameters) ProtoMessage()    {}
func (*CreateBookParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{8}
}

func (m *CreateBookParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookParameters.Unmarshal(m, b)
}
func (m *CreateBookParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookParameters.Marshal(b, m, deterministic)
}
func (m *CreateBookParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookParameters.Merge(m, src)
}
func (m *CreateBookParameters) XXX_Size() int {
	return xxx_messageInfo_CreateBookParameters.Size(m)
}
func (m *CreateBookParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookParameters.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookParameters proto.InternalMessageInfo

func (m *CreateBookParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

func (m *CreateBookParameters) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetBookParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookParameters) Reset()         { *m = GetBookParameters{} }
func (m *GetBookParameters) String() string { return proto.CompactTextString(m) }
func (*GetBookParameters) ProtoMessage()    {}
func (*GetBookParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{9}
}

func (m *GetBookParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookParameters.Unmarshal(m, b)
}
func (m *GetBookParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookParameters.Marshal(b, m, deterministic)
}
func (m *GetBookParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookParameters.Merge(m, src)
}
func (m *GetBookParameters) XXX_Size() int {
	return xxx_messageInfo_GetBookParameters.Size(m)
}
func (m *GetBookParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookParameters.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookParameters proto.InternalMessageInfo

func (m *GetBookParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

func (m *GetBookParameters) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

type DeleteBookParameters struct {
	Shelf                string   `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookParameters) Reset()         { *m = DeleteBookParameters{} }
func (m *DeleteBookParameters) String() string { return proto.CompactTextString(m) }
func (*DeleteBookParameters) ProtoMessage()    {}
func (*DeleteBookParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{10}
}

func (m *DeleteBookParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookParameters.Unmarshal(m, b)
}
func (m *DeleteBookParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookParameters.Marshal(b, m, deterministic)
}
func (m *DeleteBookParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookParameters.Merge(m, src)
}
func (m *DeleteBookParameters) XXX_Size() int {
	return xxx_messageInfo_DeleteBookParameters.Size(m)
}
func (m *DeleteBookParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookParameters.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookParameters proto.InternalMessageInfo

func (m *DeleteBookParameters) GetShelf() string {
	if m != nil {
		return m.Shelf
	}
	return ""
}

func (m *DeleteBookParameters) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "bookstore.Book")
	proto.RegisterType((*ListBooksResponse)(nil), "bookstore.ListBooksResponse")
	proto.RegisterType((*ListShelvesResponse)(nil), "bookstore.ListShelvesResponse")
	proto.RegisterType((*Shelf)(nil), "bookstore.Shelf")
	proto.RegisterType((*CreateShelfParameters)(nil), "bookstore.CreateShelfParameters")
	proto.RegisterType((*GetShelfParameters)(nil), "bookstore.GetShelfParameters")
	proto.RegisterType((*DeleteShelfParameters)(nil), "bookstore.DeleteShelfParameters")
	proto.RegisterType((*ListBooksParameters)(nil), "bookstore.ListBooksParameters")
	proto.RegisterType((*CreateBookParameters)(nil), "bookstore.CreateBookParameters")
	proto.RegisterType((*GetBookParameters)(nil), "bookstore.GetBookParameters")
	proto.RegisterType((*DeleteBookParameters)(nil), "bookstore.DeleteBookParameters")
}

func init() { proto.RegisterFile("bookstore.proto", fileDescriptor_6f82f486e563a88c) }

var fileDescriptor_6f82f486e563a88c = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x6f, 0x12, 0x41,
	0x10, 0x0e, 0x14, 0x68, 0x6f, 0x88, 0x16, 0x46, 0x8a, 0x97, 0x93, 0x52, 0xb2, 0x5a, 0xd3, 0x60,
	0xe4, 0x92, 0xfa, 0x46, 0x62, 0xb4, 0xb5, 0xa6, 0x2f, 0x3e, 0x58, 0x8c, 0x31, 0xf1, 0xc5, 0x1c,
	0xb2, 0x94, 0x4b, 0x81, 0x25, 0x77, 0x5b, 0x13, 0xd3, 0xf4, 0xc5, 0xbf, 0xe0, 0x4f, 0xf3, 0x2f,
	0xf8, 0xea, 0x7f, 0x30, 0x37, 0xbb, 0xc7, 0x1d, 0x77, 0x4b, 0x31, 0x3e, 0xc1, 0xcd, 0x7c, 0xf3,
	0xcd, 0x7c, 0x3b, 0xdf, 0xc0, 0xee, 0x50, 0x88, 0xab, 0x50, 0x8a, 0x80, 0xf7, 0x16, 0x81, 0x90,
	0x02, 0xad, 0x65, 0xc0, 0x69, 0x5d, 0x0a, 0x71, 0x39, 0xe5, 0xae, 0xb7, 0xf0, 0x5d, 0x6f, 0x3e,
	0x17, 0xd2, 0x93, 0xbe, 0x98, 0x87, 0x0a, 0xe8, 0x3c, 0xd2, 0x59, 0xfa, 0x1a, 0x5e, 0x8f, 0x5d,
	0x3e, 0x5b, 0xc8, 0xef, 0x3a, 0xd9, 0xc9, 0x26, 0x47, 0x3c, 0xfc, 0x1a, 0xf8, 0x0b, 0x29, 0x02,
	0x85, 0x60, 0x67, 0x50, 0x3a, 0x15, 0xe2, 0x0a, 0xef, 0x43, 0xd1, 0x1f, 0xd9, 0x85, 0x4e, 0xe1,
	0xc8, 0x1a, 0x14, 0xfd, 0x11, 0x36, 0xa1, 0xe2, 0x5d, 0xcb, 0x89, 0x08, 0xec, 0x22, 0xc5, 0xf4,
	0x17, 0x36, 0xa0, 0x2c, 0x7d, 0x39, 0xe5, 0xf6, 0x16, 0x85, 0xd5, 0x07, 0xeb, 0x43, 0xfd, 0x9d,
	0x1f, 0xca, 0x88, 0x29, 0x1c, 0xf0, 0x70, 0x21, 0xe6, 0x21, 0xc7, 0x43, 0x28, 0x93, 0x08, 0xbb,
	0xd0, 0xd9, 0x3a, 0xaa, 0x1e, 0xef, 0xf6, 0x12, 0x8d, 0x11, 0x70, 0xa0, 0xb2, 0xec, 0x04, 0x1e,
	0x44, 0xb5, 0x1f, 0x26, 0x7c, 0xfa, 0x8d, 0x27, 0xd5, 0x5d, 0xd8, 0x0e, 0x55, 0x48, 0xd7, 0xd7,
	0x52, 0xf5, 0x11, 0x78, 0x3c, 0x88, 0x01, 0xec, 0x04, 0xca, 0x14, 0xc9, 0xa9, 0x40, 0x28, 0xcd,
	0xbd, 0x19, 0xd7, 0x1a, 0xe8, 0x3f, 0x29, 0x98, 0xf0, 0x59, 0xa2, 0x20, 0xfa, 0x60, 0xaf, 0x60,
	0xef, 0x4d, 0xc0, 0x3d, 0xc9, 0x89, 0xe8, 0xbd, 0x17, 0x78, 0x33, 0x2e, 0x79, 0x10, 0xe2, 0x53,
	0x28, 0x47, 0x6d, 0xc6, 0xc4, 0x6a, 0x9a, 0x42, 0xa5, 0x59, 0x17, 0xf0, 0x9c, 0xcb, 0x6c, 0x75,
	0x23, 0x5d, 0x6d, 0xc5, 0xd8, 0xe7, 0xb0, 0x77, 0xc6, 0xa7, 0x3c, 0xdf, 0xcc, 0x0c, 0x7f, 0xa6,
	0x5e, 0x88, 0x5e, 0x77, 0x23, 0xf8, 0x02, 0x1a, 0x4a, 0x48, 0x04, 0xdf, 0x84, 0xc6, 0xc7, 0x50,
	0x8a, 0xf4, 0xd0, 0x03, 0x19, 0x56, 0x44, 0x49, 0xf6, 0x12, 0xea, 0xe7, 0x5c, 0xfe, 0x13, 0x1f,
	0xa6, 0xf8, 0x2c, 0x5d, 0xfe, 0x1a, 0x1a, 0x4a, 0xed, 0xff, 0x32, 0x1c, 0xff, 0xa9, 0x80, 0x75,
	0x1a, 0x4f, 0x86, 0x9f, 0xa0, 0x9a, 0x32, 0x0c, 0x36, 0x7b, 0xca, 0xe4, 0xbd, 0xd8, 0xe4, 0xbd,
	0xb7, 0xd1, 0x05, 0x38, 0xed, 0x94, 0x18, 0x83, 0xc1, 0x58, 0xed, 0xc7, 0xaf, 0xdf, 0x3f, 0x8b,
	0x80, 0x3b, 0xae, 0xb6, 0x11, 0x7e, 0x86, 0x6a, 0xca, 0x03, 0xd8, 0x49, 0x11, 0x18, 0xbd, 0xe1,
	0xe4, 0xcc, 0xc0, 0x1e, 0x12, 0x69, 0x9d, 0x2d, 0x49, 0xfb, 0x5a, 0xd6, 0x05, 0xdc, 0x4b, 0x56,
	0x7e, 0xd7, 0xd8, 0x6b, 0xe2, 0xf1, 0xb8, 0xdd, 0x64, 0xdc, 0x8f, 0xb0, 0x13, 0x3b, 0x0e, 0xf7,
	0x53, 0x93, 0xe4, 0x6d, 0x68, 0x18, 0xd4, 0x26, 0x3a, 0xc4, 0x5a, 0x4c, 0xe7, 0xde, 0xd0, 0xa0,
	0xb7, 0xe8, 0x41, 0x35, 0x65, 0xce, 0x95, 0x57, 0x30, 0x9a, 0x76, 0xed, 0xc4, 0xba, 0x45, 0x37,
	0xdf, 0xc2, 0x07, 0x6b, 0x69, 0x68, 0xcc, 0xee, 0x29, 0x63, 0x73, 0xa7, 0x65, 0xca, 0x2f, 0xb7,
	0xd8, 0xa6, 0x26, 0x36, 0x36, 0xb3, 0x4d, 0x5c, 0xaa, 0xc2, 0x11, 0x40, 0x72, 0x0e, 0x78, 0x90,
	0x5b, 0xe9, 0xaa, 0x27, 0x9d, 0xec, 0x05, 0xb0, 0x27, 0xc4, 0xdf, 0x66, 0x6b, 0xf8, 0xfb, 0x64,
	0x50, 0xfc, 0x02, 0xdb, 0xfa, 0x42, 0xb0, 0xb5, 0xba, 0x89, 0x4d, 0xfc, 0x87, 0xc4, 0x7f, 0x80,
	0xfb, 0x66, 0x7e, 0xf7, 0x26, 0xfa, 0xb9, 0xc5, 0x29, 0x40, 0x72, 0x43, 0x2b, 0x32, 0x4c, 0xa7,
	0xb5, 0x76, 0x25, 0xba, 0x5b, 0xf7, 0xee, 0x6e, 0xc3, 0x0a, 0x95, 0xbd, 0xf8, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xd6, 0xcb, 0xfd, 0x78, 0x96, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookstoreClient is the client API for Bookstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookstoreClient interface {
	ListShelves(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListShelvesResponse, error)
	CreateShelf(ctx context.Context, in *CreateShelfParameters, opts ...grpc.CallOption) (*Shelf, error)
	DeleteShelves(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetShelf(ctx context.Context, in *GetShelfParameters, opts ...grpc.CallOption) (*Shelf, error)
	DeleteShelf(ctx context.Context, in *DeleteShelfParameters, opts ...grpc.CallOption) (*empty.Empty, error)
	ListBooks(ctx context.Context, in *ListBooksParameters, opts ...grpc.CallOption) (*ListBooksResponse, error)
	CreateBook(ctx context.Context, in *CreateBookParameters, opts ...grpc.CallOption) (*Book, error)
	GetBook(ctx context.Context, in *GetBookParameters, opts ...grpc.CallOption) (*Book, error)
	DeleteBook(ctx context.Context, in *DeleteBookParameters, opts ...grpc.CallOption) (*empty.Empty, error)
}

type bookstoreClient struct {
	cc *grpc.ClientConn
}

func NewBookstoreClient(cc *grpc.ClientConn) BookstoreClient {
	return &bookstoreClient{cc}
}

func (c *bookstoreClient) ListShelves(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListShelvesResponse, error) {
	out := new(ListShelvesResponse)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/ListShelves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) CreateShelf(ctx context.Context, in *CreateShelfParameters, opts ...grpc.CallOption) (*Shelf, error) {
	out := new(Shelf)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/CreateShelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) DeleteShelves(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/DeleteShelves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) GetShelf(ctx context.Context, in *GetShelfParameters, opts ...grpc.CallOption) (*Shelf, error) {
	out := new(Shelf)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/GetShelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) DeleteShelf(ctx context.Context, in *DeleteShelfParameters, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/DeleteShelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) ListBooks(ctx context.Context, in *ListBooksParameters, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) CreateBook(ctx context.Context, in *CreateBookParameters, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) GetBook(ctx context.Context, in *GetBookParameters, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) DeleteBook(ctx context.Context, in *DeleteBookParameters, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookstoreServer is the server API for Bookstore service.
type BookstoreServer interface {
	ListShelves(context.Context, *empty.Empty) (*ListShelvesResponse, error)
	CreateShelf(context.Context, *CreateShelfParameters) (*Shelf, error)
	DeleteShelves(context.Context, *empty.Empty) (*empty.Empty, error)
	GetShelf(context.Context, *GetShelfParameters) (*Shelf, error)
	DeleteShelf(context.Context, *DeleteShelfParameters) (*empty.Empty, error)
	ListBooks(context.Context, *ListBooksParameters) (*ListBooksResponse, error)
	CreateBook(context.Context, *CreateBookParameters) (*Book, error)
	GetBook(context.Context, *GetBookParameters) (*Book, error)
	DeleteBook(context.Context, *DeleteBookParameters) (*empty.Empty, error)
}

// UnimplementedBookstoreServer can be embedded to have forward compatible implementations.
type UnimplementedBookstoreServer struct {
}

func (*UnimplementedBookstoreServer) ListShelves(ctx context.Context, req *empty.Empty) (*ListShelvesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShelves not implemented")
}
func (*UnimplementedBookstoreServer) CreateShelf(ctx context.Context, req *CreateShelfParameters) (*Shelf, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShelf not implemented")
}
func (*UnimplementedBookstoreServer) DeleteShelves(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShelves not implemented")
}
func (*UnimplementedBookstoreServer) GetShelf(ctx context.Context, req *GetShelfParameters) (*Shelf, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShelf not implemented")
}
func (*UnimplementedBookstoreServer) DeleteShelf(ctx context.Context, req *DeleteShelfParameters) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShelf not implemented")
}
func (*UnimplementedBookstoreServer) ListBooks(ctx context.Context, req *ListBooksParameters) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (*UnimplementedBookstoreServer) CreateBook(ctx context.Context, req *CreateBookParameters) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedBookstoreServer) GetBook(ctx context.Context, req *GetBookParameters) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookstoreServer) DeleteBook(ctx context.Context, req *DeleteBookParameters) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}

func RegisterBookstoreServer(s *grpc.Server, srv BookstoreServer) {
	s.RegisterService(&_Bookstore_serviceDesc, srv)
}

func _Bookstore_ListShelves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).ListShelves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/ListShelves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).ListShelves(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_CreateShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShelfParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).CreateShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/CreateShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).CreateShelf(ctx, req.(*CreateShelfParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_DeleteShelves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).DeleteShelves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/DeleteShelves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).DeleteShelves(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_GetShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).GetShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/GetShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).GetShelf(ctx, req.(*GetShelfParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_DeleteShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShelfParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).DeleteShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/DeleteShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).DeleteShelf(ctx, req.(*DeleteShelfParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).ListBooks(ctx, req.(*ListBooksParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).CreateBook(ctx, req.(*CreateBookParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).GetBook(ctx, req.(*GetBookParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).DeleteBook(ctx, req.(*DeleteBookParameters))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bookstore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookstore.Bookstore",
	HandlerType: (*BookstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListShelves",
			Handler:    _Bookstore_ListShelves_Handler,
		},
		{
			MethodName: "CreateShelf",
			Handler:    _Bookstore_CreateShelf_Handler,
		},
		{
			MethodName: "DeleteShelves",
			Handler:    _Bookstore_DeleteShelves_Handler,
		},
		{
			MethodName: "GetShelf",
			Handler:    _Bookstore_GetShelf_Handler,
		},
		{
			MethodName: "DeleteShelf",
			Handler:    _Bookstore_DeleteShelf_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _Bookstore_ListBooks_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _Bookstore_CreateBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Bookstore_GetBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Bookstore_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookstore.proto",
}
